  on:
    push:
      branches:
        - main
  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Find and Replace
          run: |
            sed -i 's/email_address_replace_me/${{ secrets.EMAIL }}/g' cert-manager/prod_issuer.yaml && \
            sed -i 's/email_address_replace_me/${{ secrets.EMAIL }}/g' cert-manager/stagging_issuer.yaml
        - uses: Azure/setup-kubectl@v4
        - uses: Azure/k8s-set-context@v4
          with:
            kubeconfig: ${{ secrets.KUBE_CONFIG }}
        - uses: Azure/k8s-deploy@v5
          with:
            resource-group: cluster1
            name: cluster1
            action: deploy
            strategy: basic
            manifests: |
              example-service/echo.yaml
              example-service/ingress.yaml
        - uses: Azure/k8s-deploy@v5
          with:
            namespace: "ingress-nginx"
            resource-group: cluster1
            name: cluster1
            action: deploy
            strategy: basic
            manifests: |
              nginx/nginx.yaml
        - uses: Azure/k8s-deploy@v5
          with:
            namespace: "cert-manager"
            resource-group: cluster1
            name: cluster1
            action: deploy
            strategy: basic
            manifests: |
              cert-manager/cert-manager.yaml
              cert-manager/prod_issuer.yaml
              cert-manager/staging_issuer.yaml
        - uses: Azure/k8s-deploy@v5
          with:
            namespace: "kube-system"
            resource-group: cluster1
            name: cluster1
            action: deploy
            strategy: basic
            manifests: |
              cert-manager/cert-manager-kube-system.yaml 
