  on:
    push:
      branches:
        - main
  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - uses: Azure/setup-kubectl@v4
        - uses: Azure/k8s-set-context@v4
          with:
            kubeconfig: ${{ secrets.KUBE_CONFIG }}
        - uses: Azure/k8s-deploy@v5
          with:
            #resource-group: yourResourceGroup
            name: cluster1
            action: deploy
            strategy: basic

            private-cluster: true
            manifests: |
              cert-manager/cert-manager.yaml
              nginx/nginx.yaml
              example-service/echo.yaml
